/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Downtown_Dengue.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Downtown_Dengue.gltf')
  return (
    <div></div>
    // <group {...props} dispose={null}>
    //   <group position={[15.76, 46.13, 12.42]} scale={100}>
    //     <mesh geometry={nodes.Block_Number_1.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Block_Number_2.geometry} material={materials.Bamboo} />
    //   </group>
    //   <mesh geometry={nodes.Rubbish_Bag.geometry} material={materials.Bamboo} position={[10.76, 9.58, -21.23]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_1.geometry} material={materials.Bamboo} position={[14, 9.92, -20.41]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_2.geometry} material={materials.Bamboo} position={[12.55, 10, -19.91]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_3.geometry} material={materials.Bamboo} position={[12.28, 10.2, -17.04]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_4.geometry} material={materials.Bamboo} position={[11.35, 9.85, -18.56]} scale={100} />
    //   <mesh geometry={nodes.Carton_Box.geometry} material={materials['Plant pot']} position={[-11.86, 6.19, -18.39]} scale={100} />
    //   <mesh geometry={nodes.Carton_Box_1.geometry} material={materials['Plant pot']} position={[-12.1, 3.7, -18.55]} scale={100} />
    //   <mesh geometry={nodes.Broom.geometry} material={materials.Ground} position={[-11.58, 39.71, -6.71]} scale={100} />
    //   <mesh geometry={nodes.Carton_Box_2.geometry} material={materials['Plant pot']} position={[-6.48, 3.74, -20.26]} scale={100} />
    //   <mesh geometry={nodes.Dust_Pan.geometry} material={materials.Ground} position={[-11.01, 39.4, -7.59]} scale={100} />
    //   <mesh geometry={nodes.Broom_1.geometry} material={materials.Ground} position={[10.52, 4.08, -6.63]} scale={100} />
    //   <mesh geometry={nodes.Dust_Pan_1.geometry} material={materials.Ground} position={[6.38, 3.76, -7.35]} scale={100} />
    //   <mesh geometry={nodes.Watering_Can.geometry} material={materials['Yellow Clothes']} position={[-11.37, 30.13, -0.24]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_5.geometry} material={materials.Bamboo} position={[-1.21, 8.58, -26]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_6.geometry} material={materials.Bamboo} position={[2.24, 7.35, -23.96]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_7.geometry} material={materials.Bamboo} position={[2.5, 10.6, -26.55]} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Bag_8.geometry} material={materials.Bamboo} position={[-2.09, 10.29, -25.04]} scale={100} />
    //   <group scale={100}>
    //     <mesh geometry={nodes.Building_1.geometry} material={materials['Base Yellow']} />
    //     <mesh geometry={nodes.Building_2.geometry} material={materials['Grey Concrete']} />
    //     <mesh geometry={nodes.Building_3.geometry} material={materials['Orange Highlights']} />
    //     <mesh geometry={nodes.Building_4.geometry} material={materials['Windows Transparent']} />
    //   </group>
    //   <mesh geometry={nodes.Windows_BG.geometry} material={materials['Windows Diffuse']} scale={100} />
    //   <mesh geometry={nodes.Rubbish_Truck.geometry} material={materials['Truck Diffuse']} position={[-0.12, 3.73, -35.38]} scale={100} />
    //   <mesh geometry={nodes.Voideck_Chairs.geometry} material={materials['Grey Concrete']} position={[0, 3.75, 0.79]} scale={100} />
    //   <mesh geometry={nodes.Bamboo_Holder.geometry} material={materials['Grey Concrete']} position={[-6.86, 19.39, 13.07]} scale={100} />
    //   <mesh geometry={nodes.Bamboo_Holder_1.geometry} material={materials['Grey Concrete']} position={[-7.36, 30.65, 13.98]} scale={100} />
    //   <mesh geometry={nodes.Bamboo_Holder_2.geometry} material={materials['Grey Concrete']} position={[-7.92, 42.34, 14.85]} scale={100}>
    //     <mesh geometry={nodes.Bamboo_Poles.geometry} material={materials.Bamboo} position={[0, 0, 0.03]}>
    //       <mesh geometry={nodes.Clothes.geometry} material={materials.clothes} position={[0.17, 0, 0.01]} />
    //       <mesh geometry={nodes.Clothes_1.geometry} material={materials.Pails} position={[-0.02, 0, 0.08]} />
    //       <mesh geometry={nodes.Clothes_2.geometry} material={materials.clothes} position={[-0.02, 0, 0]} />
    //       <mesh geometry={nodes.Clothes_3.geometry} material={materials['Plant pot']} position={[0.02, 0, 0]} />
    //       <mesh geometry={nodes.Clothes_4.geometry} material={materials.Clothes} position={[0.15, 0, 0.03]} />
    //       <mesh geometry={nodes.Clothes001.geometry} material={materials.Clothes} position={[-0.01, -0.01, 0.03]} />
    //     </mesh>
    //   </mesh>
    //   <mesh geometry={nodes.Bamboo_Holder_3.geometry} material={materials['Grey Concrete']} position={[-8.25, 54.51, 15.72]} scale={100}>
    //     <mesh geometry={nodes.Bamboo_Poles_1.geometry} material={materials.Bamboo}>
    //       <mesh geometry={nodes.Clothes_5.geometry} material={materials.clothes} position={[-0.01, 0, 0.09]} />
    //       <mesh geometry={nodes.Clothes_6.geometry} material={materials.Pails} position={[-0.01, 0, 0.03]} />
    //     </mesh>
    //   </mesh>
    //   <mesh geometry={nodes.Bamboo_Holder_4.geometry} material={materials['Grey Concrete']} position={[7.97, 19.26, 13.07]} scale={100}>
    //     <mesh geometry={nodes.Bamboo_Poles_2.geometry} material={materials.Bamboo}>
    //       <mesh geometry={nodes.Clothes_7.geometry} material={materials.clothes} position={[-0.02, -0.01, 0.05]} />
    //     </mesh>
    //   </mesh>
    //   <mesh geometry={nodes.Bamboo_Holder_5.geometry} material={materials['Grey Concrete']} position={[8.19, 30.64, 13.98]} scale={100}>
    //     <mesh geometry={nodes.Bamboo_Poles_3.geometry} material={materials.Bamboo}>
    //       <mesh geometry={nodes.Clothes_8.geometry} material={materials['Plant pot']} position={[0.01, 0, 0.07]} />
    //       <mesh geometry={nodes.Clothes_9.geometry} material={materials.Pails} position={[0.02, 0, 0.04]} />
    //     </mesh>
    //   </mesh>
    //   <mesh geometry={nodes.Bamboo_Holder_6.geometry} material={materials['Grey Concrete']} position={[8.75, 42.43, 14.85]} scale={100}>
    //     <mesh geometry={nodes.Bamboo_Poles_4.geometry} material={materials.Bamboo} />
    //   </mesh>
    //   <mesh geometry={nodes.Bamboo_Holder_7.geometry} material={materials['Grey Concrete']} position={[8.97, 54.46, 15.72]} scale={100} />
    //   <group position={[-11.28, 27.81, 2.56]} scale={100}>
    //     <mesh geometry={nodes.Empty_Pail_6.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Empty_Pail_7.geometry} material={materials.Pails} />
    //   </group>
    //   <group position={[-11.36, 28.52, 2.75]} scale={100}>
    //     <mesh geometry={nodes.Empty_Pail_8.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Empty_Pail_9.geometry} material={materials.Pails} />
    //   </group>
    //   <group position={[-11.31, 29.3, 2.63]} scale={100}>
    //     <mesh geometry={nodes.Empty_Pail_10.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Empty_Pail_11.geometry} material={materials.Pails} />
    //   </group>
    //   <group position={[-10.38, 30.46, -2.64]} scale={100}>
    //     <mesh geometry={nodes.Empty_Pail_12.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Empty_Pail_13.geometry} material={materials.Pails} />
    //   </group>
    //   <group position={[-11.15, 30.26, 2.26]} scale={100}>
    //     <mesh geometry={nodes.Empty_Pail_14.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Empty_Pail_15.geometry} material={materials.Pails} />
    //   </group>
    //   <mesh geometry={nodes.Flower_Vase.geometry} material={materials.Clothes} position={[13.63, 54.25, -10.81]} scale={100} />
    //   <mesh geometry={nodes.Flower_Vase_1.geometry} material={materials.Clothes} position={[13.32, 54.25, -9.23]} scale={100} />
    //   <group position={[-11.19, 30.96, 2.38]} scale={100}>
    //     <mesh geometry={nodes.Empty_Pail_16.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Empty_Pail_17.geometry} material={materials.Pails} />
    //   </group>
    //   <mesh geometry={nodes.Bench.geometry} material={materials.Bamboo} position={[-9.43, 4.83, 12.66]} scale={100} />
    //   <mesh geometry={nodes.Bench_1.geometry} material={materials.Bamboo} position={[-11.33, 28.92, -2.72]} scale={100} />
    //   <group position={[-12.3, 3.94, 12.4]} scale={100}>
    //     <mesh geometry={nodes.Potted__plant_small_1.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Potted__plant_small_2.geometry} material={materials['Plant pot']} />
    //     <mesh geometry={nodes.Potted__plant_small_3.geometry} material={materials['Round Plant']} />
    //     <mesh geometry={nodes.Potted__plant_small_4.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <group position={[-13.29, 3.74, 9.04]} scale={100}>
    //     <mesh geometry={nodes.Potted_plant_5.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Potted_plant_6.geometry} material={materials['Plant pot']} />
    //     <mesh geometry={nodes.Potted_plant_7.geometry} material={materials['Round Plant']} />
    //     <mesh geometry={nodes.Potted_plant_8.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <mesh geometry={nodes.Plant_Tray009.geometry} material={materials['Plant pot']} position={[-10.65, 16.68, -5.8]} scale={100} />
    //   <mesh geometry={nodes.Curb.geometry} material={materials['Base Yellow']} position={[0.14, 0, 0]} scale={100} />
    //   <mesh geometry={nodes.Plants.geometry} material={materials.Ground} scale={100} />
    //   <mesh geometry={nodes.Ground.geometry} material={materials.Ground} position={[0, 1.86, -1.66]} scale={100} />
    //   <group position={[-10.79, 16.73, -5.58]} scale={100}>
    //     <mesh geometry={nodes.Potted_plant_9.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Potted_plant_10.geometry} material={materials['Plant pot']} />
    //     <mesh geometry={nodes.Potted_plant_11.geometry} material={materials['Round Plant']} />
    //     <mesh geometry={nodes.Potted_plant_12.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <group position={[-11.72, 39.47, 1.54]} scale={100}>
    //     <mesh geometry={nodes.Potted_plant_13.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Potted_plant_14.geometry} material={materials['Plant pot']} />
    //     <mesh geometry={nodes.Potted_plant_15.geometry} material={materials['Round Plant']} />
    //     <mesh geometry={nodes.Potted_plant_16.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <mesh geometry={nodes.Plant_Tray010.geometry} material={materials['Plant pot']} position={[-12.04, 39.4, 1.58]} scale={100} />
    //   <group position={[-12.55, 50.87, -6.06]} scale={100}>
    //     <mesh geometry={nodes.Potted_plant_17.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Potted_plant_18.geometry} material={materials['Plant pot']} />
    //     <mesh geometry={nodes.Potted_plant_19.geometry} material={materials['Round Plant']} />
    //     <mesh geometry={nodes.Potted_plant_20.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <mesh geometry={nodes.Plant_Tray011.geometry} material={materials['Plant pot']} position={[-12.82, 50.81, -6.12]} scale={100} />
    //   <group position={[-12.21, 50.81, -8.36]} scale={100}>
    //     <mesh geometry={nodes.Potted_plant_21.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Potted_plant_22.geometry} material={materials['Plant pot']} />
    //     <mesh geometry={nodes.Potted_plant_23.geometry} material={materials['Round Plant']} />
    //     <mesh geometry={nodes.Potted_plant_24.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <mesh geometry={nodes.Plant_Tray012.geometry} material={materials['Plant pot']} position={[-12.51, 50.74, -8.74]} scale={100} />
    //   <mesh geometry={nodes.Aircon.geometry} material={materials['Windows Diffuse']} position={[16.09, 52.63, 3.72]} scale={100} />
    //   <mesh geometry={nodes.Aircon_1.geometry} material={materials['Windows Diffuse']} position={[15.02, 41.08, 3.56]} scale={100} />
    //   <mesh geometry={nodes.Aircon_2.geometry} material={materials['Windows Diffuse']} position={[13.58, 18.11, 1.46]} scale={100} />
    //   <group position={[11.59, 4.62, -20.17]} scale={100}>
    //     <mesh geometry={nodes.Rubbish_bin_1.geometry} material={materials['Pail handle']} />
    //     <mesh geometry={nodes.Rubbish_bin_2.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Rubbish_bin_3.geometry} material={materials['Round plant 2']} />
    //     <mesh geometry={nodes.Rubbish_bin_Cover.geometry} material={materials['Round plant 2']} position={[-0.02, 0.06, 0.02]} />
    //   </group>
    //   <group position={[13.32, 56.25, -8.98]} scale={100}>
    //     <mesh geometry={nodes.Flowers_2.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Flowers_3.geometry} material={materials.Pails} />
    //     <mesh geometry={nodes.Flowers_4.geometry} material={materials.Clothes} />
    //   </group>
    //   <group position={[13.49, 55.73, -10.91]} scale={100}>
    //     <mesh geometry={nodes.Flowers_5.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Flowers_6.geometry} material={materials.Pails} />
    //     <mesh geometry={nodes.Flowers_7.geometry} material={materials.Clothes} />
    //   </group>
    //   <group position={[-23.71, 3.56, -13.92]} scale={100}>
    //     <mesh geometry={nodes.Tree_3.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Tree_4.geometry} material={materials['Round Plant']} />
    //   </group>
    //   <group position={[-24.58, 3.71, -14.7]} scale={100}>
    //     <mesh geometry={nodes.Tree_5.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Tree_6.geometry} material={materials['Round plant 2']} />
    //   </group>
    //   <group position={[23.76, 3.69, -12.98]} scale={100}>
    //     <mesh geometry={nodes.Tree_7.geometry} material={materials.Bamboo} />
    //     <mesh geometry={nodes.Tree_8.geometry} material={materials['Round Plant']} />
    //   </group>
    //   <mesh geometry={nodes.Rocks.geometry} material={materials['Grey Concrete']} scale={100} />
    //   <mesh geometry={nodes.Truck_Windows.geometry} material={materials['Truck windows']} position={[-0.12, 3.73, -35.38]} scale={100} />
    // </group>
  )
}

// useGLTF.preload('/Downtown_Dengue.gltf')
